### ISSUE TITLE
Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by rubenberendsen** [Domitnator/kenticocloud-nuxt-module#3]
**Code:**
computed: {
    getContent() {
      return this.$deliveryClient.items()
      .type('homepage')
      .get()
      .subscribe(response => console.log('DeliveryClient Response', response));
    }
  },

**TypeError**
Cannot read property 'items' of undefined

**Comment by Domitnator** [comment]
Hi @rubenberendsen ,

I published a new release! 

To problem is that Nuxt only supports Promises. The example in the readme.md i was giving was using 
 the observable operator of [rxjs](http://reactivex.io/rxjs/). So i therefor updated the readme.md.

Client side call are now working as expected! 

For server side call's however, there is still a rxjs issue but i created a new bug for that: #5
