### ISSUE TITLE
Downgrade of Kentico SDK

### ISSUE THREAD

**Issue by Enngage** [Domitnator/kenticocloud-nuxt-module#4]
Hi there, 

I was curious as to why you downgraded from `kentico-cloud-delivery-typescript-sdk` from `3.1.0 `to `2.5.3`. Could you let me know some more details?

I've made some significant changes to the build process, suppose this has to do with that?  

Anyway, I'm working on refactoring pretty much the whole SDK and this might help me figure out what I did wrong. Thanks!

**Comment by Domitnator** [comment]
Hi @Enngage ,

Funny, I actually wanted to contact you next week about some issues I have with implementing the kentico-js-sdk in a Nuxt environment. So i am glad you reached out to me.

I started this repo because i work a lot with Kentico(Cloud) and i am a great fan of Nuxtjs ánd to prevent to repetitive task of setting up the KenticoCloudDeliveryTypeScriptSDK.

Yesterday I found the issue which I was running into ( #3  ), the error is somewhat misleading but it is the rxjs which is causing that problem as Nuxt supports only promises (in it's default work). So client side calls can now be done!

I'm still having problems however getting the server-call to work. I keep getting the error: 

"XMLHttpRequest is not supported by your browser"

![image](https://user-images.githubusercontent.com/13468638/38471447-7f36f87e-3b71-11e8-8777-cda91ab3262e.png)

Next week i will digg into it a bit more. But i am sure it has something to do with rxjs as well. 

Nice to hear that you are refactoring the SDK. As for me, it would be great if rxjs would be optional (or an extension). I think for most of the projects promisses are sufficient enough.

**Comment by Enngage** [comment]
Lucky coincidence :) I think I might able to point you to right direction with points you mentioned:

1) The whole SDK is built on top of `rxjs` which I believe is superior to Promises so I don't think this is gonna change, but from a consumer point of view, it should't make a difference because `Observable` can be easily converted to a `Promise`  (see [rxjs docs](https://www.learnrxjs.io/operators/utility/topromise.html)) so you would be able to do something like: 

```javascript
let promise = deliveryClient.items().get().toPromise()
```
I'm in a middle of refactoring to `rxjs 6` so the syntax will change a bit, but the general idea will be the same.

2) The problem you have with `XMLHttpRequest` is because this class is implemented by browsers (Firefox, Google, Opera ...), but does not have any implementation in Node.js. There are other HTTP clients for node.js, but they work quite differently so any code that needs to make HTTP requests need to use different libraries based on the environment. Previously, I had support for both node.js and browser in the same SDK, but that turned out to be a bad idea beacuse bundling such libraries (i.e. via webpack for production) will fail because you can't for example bundle node.js code for use in browser - browser doesn't know about the classes and will throw exceptions (and vice versa)

Thats why I separated the code into [KenticoCloudDeliveryNodeSDK](https://github.com/Enngage/KenticoCloudDeliveryNodeSDK). This library depends on the main one and only implements HTTP service, but its not up to date yet (I will bump this up with the release of the new version). 

Though, I'm not sure why you downgraded the library as the above was not changed in v3, only the build process was.

**Comment by Domitnator** [comment]
1. Yes, the toPromise method works fine! So yesterday i updated the readme.md and i also upgraded the kentico-cloud-delivery-typescript-sdk package to version 3.1.0 again. 

2. I also did a quick test to see if i could do a server-side-call with the kentico-cloud-delivery-node-sdk in my nuxt test application and that works too! So in theory i could add another global plugin ($deliveryNodeClient for instance) but then the user has to be aware of using $deliveryNodeClient server-side and $deliveryClient client-side. I guess this can be confusing at first and is error-prone. Take [Axios](https://axios.nuxtjs.org/usage.html) for instance. It is always $axios to do a http-call, no matter if you are client or server side. 

I have to think about this some more. Maybe i can come up with another solution, i know there are ways to detect if the call is done server or client side within nuxt so maybe that could help me out (by using a factory for instance).

**Comment by Enngage** [comment]
Awesome :) I totally forgot you can get promise just by calling `getPromise` method that I've prepared in the past:
```javascript
let promise = deliveryClient.items().getPromise()
```
In v4 I've changed this so you either call `getObservable` or `getPromise`. 

I actually didn't know about Axios. I've been researching http clients and finally decided to go with `xhr` in v4 (as a substite for `rxdom`). I think I'll have to rethink this because the Axios looks really good and my tests seems to be working with it perfectly fine. 

One thing that I'll have to test is how it bundles up with WebPack and if there are any dynamic includes or anything that would break AOT builds. 

It would be awesome to have the library working both in node and browser and this could solve one part of the issue, the other is HTML parser. There currently isn't any node.js/browser parser apart from Parse5 which I wan't to get rid of.. 

Anyway - maybe wait with the server side NUXT client a bit.

**Comment by Enngage** [comment]
Turns out the Axios is pretty good and I'll be using that for the library. Seems like I will deprecate the node client afterall. 

If you want to test it, try installing beta version `4.0.0-beta.5` which should now work in both browser & node. Note that there are some [API changes](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/releases/tag/v4.0.0-beta-5), which should be fixed in docs - https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/tree/major-version-node-js-support

**Comment by Domitnator** [comment]
@Enngage : Cool, thanks for the update! Axios FTW!

I have little time this week but hopefully I find some time to check it out. I'll keep you posted!

**Comment by Domitnator** [comment]
I just did a quick test to see if it works but i am getting an error:

I am running this piece of code:


```
this.$deliveryClient
    .items()
    .type('page')
    .getPromise()
    .then(response => console.log('DeliveryClient Response', response));
```

But that is giving me this error:

![image](https://user-images.githubusercontent.com/13468638/38828286-e3bff68e-41b5-11e8-95ca-8ed58cb435a9.png)

![image](https://user-images.githubusercontent.com/13468638/38828398-3e1af2e6-41b6-11e8-8fe6-0f26ed0e2184.png)


Do you have any clue what is going wrong?

**Comment by Enngage** [comment]
Thanks a lot for trying that out. Since the rxjs is marked as peer
dependency, it means it is not automatically installed/updated. Can you try
changing the rxjs to latest version (currently its RC -> *'6.0.0-uncanny-rc.7'
*) in your package.json and install it?

**Comment by Domitnator** [comment]
Great, it works now!! I actually got a warning for installing rxjs but ignored it because i was in a hurry.

I will release a new version this afternoon so we can do some more testing internally! But this sure looks promising!

Any roadmap for releasing this (major-version-node-js-support) branch/version as a production version?

**Comment by Enngage** [comment]
Glad to hear that! I'm still figuring out the dependencies. I've made some
UMD boundles which don't need external rxjs to work and it can be used as
easily as this -
https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/blob/major-version-node-js-support/demo/umd-promise/index.html


However, if you are building your library using the ES2015 or CommonJS
source, you are responsible for bundling and I'm not sure what kind of
dependency is needed (optional vs peer?)

I'm sure that I will wait at least until rxjs 6 is released as a stable
release. We are using this library internally as well so I want to see if
we encounter any other issue too.

**Comment by Domitnator** [comment]
Closed this issue because the new Kentico Cloud Delivery SDK is implemented!
